# ??????
# @author <a href="https://github.com/liyupi">?????</a>
# @from <a href="https://yupi.icu">????????</a>
spring:
  application:
    name: yuoj-backend-user-service
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuoj
    username: root
    password: 613511
  # Redis ??
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  address: 0.0.0.0
  port: 8102
#  ssl:
#    key-store-password: yuopc0xy    #填写jks-password.txt文件内的密码。
#    key-store-type: JKS #JKS格式证书密钥库类型。PFX格式的证书密钥库类型为PKCS12。
#    key-store: classpath:aliyun.xw612.cn.jks   #您需要使用实际的证书名称替换domain_name.jks。
  servlet:
    context-path: /api/user
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# ??????
codesandbox:
  type: remote
knife4j:
  enable: true